# Utilise la dernière image de base Ubuntu
FROM ubuntu:latest

# Met à jour l'index des paquets APT
RUN apt-get update

# Met à niveau les logiciels actuellement installés
RUN apt-get upgrade -y

# Commande pour afficher "Hello, World!" lors de l'exécution du conteneur
CMD ["echo", "Hello, World!"] 
